### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by Keith-S-Thompson** [arjun024/strbuf#1]
The URL

https://www.kernel.org/pub/software/scm/git/docs/technical/api-strbuf.html

in `README.md` does not work. This does:

https://www.kernel.org/pub/software/scm/git/docs/v2.3.4/technical/api-strbuf.html

It appears there's a copy for each git release. I don't see a link to the latest version that updates with new releases. I don't know whether v2.3.4 is the best version to use (it's what I found in a quick Google search).

**Comment by arjun024** [comment]
Thanks. Merged. See 118e537b65c9c475b0b6389e3a5f49a56c737514
